### ISSUE TITLE
Old version worked once

### ISSUE THREAD

**Issue by pdxpilot** [astenlund/fs2ff#2]
I downloaded the old version a few days ago and worked one time. Upon other attempts it says connected but doesn’t show up under device list on FF. Does new version overwrite old version?

**Comment by astenlund** [comment]
No, there is no auto-update functionality, so you're still running the same version that you downloaded. From v0.1.2 and forward, you can see the version number in the title bar of the app window. For earlier versions, you can view the version number by right-clicking fs2ff.exe and selecting Properties -> Details.

As to the connection issues: The app can unfortunately only know the status of the connection to Flight Simulator, not the one to ForeFlight. This is because ForeFlight only listens to UDP traffic, which is connectionless (i.e. the data packets are sent in a fire-and-forget manner). Version 0.1.3 of my app, however, added the option to send the data packets directly to the iPad/iPhone, by means of letting you enter the IP address of the device. This direct mode is much more stable in my experience, so you could give that a go if you haven't already.

Please let me know if the [latest release](https://github.com/astenlund/fs2ff/releases/latest) works any better for you.

/Andreas

**Comment by astenlund** [comment]
Closing this, since I haven't heard back. If there are still problems with the newest version, make sure to turn off broadcast mode. If that doesn't help, please create a new issue with a more detailed description and I will have a look.
